### ISSUE TITLE
Slight bug in printed message

### ISSUE THREAD

**Issue by luispfonseca** [betanalpha/mcmc_diagnostics#1]
https://github.com/betanalpha/mcmc_diagnostics/blob/4b60c7d4fb2b9e37fce340b9c4026b7edf9af65d/rstan/stan_utility_rstan.R#L62

I think the `n` variable should be changed to `c` in this row, leading to:

```r
cat(sprintf('Chain %s: E-FMI = %s.\n', c, numer / denom)) 
```

**Comment by betanalpha** [comment]
Yes, absolutely correct.  I'll push a correction in just a bit.

**Comment by betanalpha** [comment]
Thanks!  Resolved in https://github.com/betanalpha/mcmc_diagnostics/commit/b179251d61e83645d3a0b58c93e0f93fce5b37fd.
